# Generated by Django 2.1.7 on 2019-03-12 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='submitted_by',
            field=models.ForeignKey(default=1, help_text='The user which submitted the game.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='datetime_played',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the game was played.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1',
            field=models.ForeignKey(help_text='One of the players.', on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='api.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player1_score',
            field=models.PositiveSmallIntegerField(default=0, help_text="Player 1's score."),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2',
            field=models.ForeignKey(help_text='The other player.', on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='api.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player2_score',
            field=models.PositiveSmallIntegerField(default=0, help_text="Player 2's score."),
        ),
    ]
