# Generated by Django 2.1.7 on 2019-03-14 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('api', '0005_auto_20190314_1209'), ('api', '0006_auto_20190314_1210'), ('api', '0007_auto_20190314_1212'), ('api', '0008_auto_20190314_1212')]

    dependencies = [
        ('api', '0004_player_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player1',
            new_name='winner',
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(help_text='One of the players.', on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='api.Player'),
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player2',
            new_name='loser',
        ),
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(help_text='The other player.', on_delete=django.db.models.deletion.PROTECT, related_name='loser', to='api.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(help_text="The game's loser.", on_delete=django.db.models.deletion.PROTECT, related_name='loser', to='api.Player'),
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player1_score',
            new_name='winner_score',
        ),
        migrations.AlterField(
            model_name='game',
            name='winner_score',
            field=models.PositiveSmallIntegerField(default=8, help_text="The winner's score."),
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player2_score',
            new_name='loser_score',
        ),
        migrations.AlterField(
            model_name='game',
            name='loser_score',
            field=models.PositiveSmallIntegerField(default=0, help_text="The loser's score."),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(help_text="The game's winner.", on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='api.Player'),
        ),
    ]
