# Generated by Django 2.2 on 2019-04-25 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190315_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatsNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.PositiveIntegerField(help_text='The number of wins the player has')),
                ('losses', models.PositiveIntegerField(help_text='The number of losses the player has')),
                ('average_goals_per_game', models.PositiveSmallIntegerField(help_text='The average number of goals scored per game by the player')),
                ('game', models.ForeignKey(help_text="The latest game which updated the player's stats.", on_delete=django.db.models.deletion.CASCADE, to='api.Game')),
                ('player', models.ForeignKey(help_text='The player to record stats for.', on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
            ],
        ),
    ]
