# Generated by Django 2.2 on 2019-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_playerstatsnode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatsnode',
            name='average_goals_per_game',
            field=models.FloatField(help_text='The average number of goals scored per game by the player'),
        ),
    ]
