# Generated by Django 2.2 on 2019-04-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190425_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime_played',
            field=models.DateTimeField(auto_now_add=True, help_text='The date and time when the game was played.'),
        ),
    ]
