# Generated by Django 2.2 on 2019-04-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190425_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstatsnode',
            name='games',
            field=models.PositiveIntegerField(default=0, help_text='The number of games a player has played.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerstatsnode',
            name='average_goals_per_game',
            field=models.FloatField(help_text='The average number of goals scored per game by the player.'),
        ),
        migrations.AlterField(
            model_name='playerstatsnode',
            name='losses',
            field=models.PositiveIntegerField(help_text='The number of losses the player has.'),
        ),
        migrations.AlterField(
            model_name='playerstatsnode',
            name='wins',
            field=models.PositiveIntegerField(help_text='The number of wins the player has.'),
        ),
    ]
