# Generated by Django 2.2 on 2019-04-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190426_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerRatingsNode',
            new_name='PlayerRatingNode',
        ),
    ]
