# Generated by Django 2.2 on 2019-04-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190426_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchupstatsnode',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='playerratingnode',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='playerstatsnode',
            options={'ordering': ['-id']},
        ),
    ]
