# Generated by Django 2.2 on 2019-04-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20190426_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerratingnode',
            name='inactivity',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many rating periods the player has been inactive for.'),
            preserve_default=False,
        ),
    ]
