# Generated by Django 2.2 on 2019-05-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_playerratingnode_inactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerratingnode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the player was considered active during this rating period.'),
            preserve_default=False,
        ),
    ]
