# Generated by Django 2.2 on 2019-05-09 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190503_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupstatsnode',
            name='win_rate',
            field=models.FloatField(default=0, help_text="player1's win rate against player2."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerstatsnode',
            name='win_rate',
            field=models.FloatField(default=0, help_text="The player's win rate."),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerratingnode',
            name='rating_period',
            field=models.ForeignKey(help_text='The rating period this rating was calculated in.', on_delete=django.db.models.deletion.CASCADE, to='api.RatingPeriod'),
        ),
    ]
