# Generated by Django 2.2 on 2019-05-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20190508_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerratingnode',
            name='ranking',
            field=models.PositiveSmallIntegerField(help_text="The player's rating for this rating period.", null=True),
        ),
        migrations.AddField(
            model_name='playerratingnode',
            name='ranking_delta',
            field=models.SmallIntegerField(help_text="The player's rating change for this rating period.", null=True),
        ),
    ]
