# Generated by Django 2.1.7 on 2019-03-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190311_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime_played',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
