# Generated by Django 2.1.7 on 2019-03-11 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190311_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='datetime_played',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
